root = "."
tmp_dir = "tmp"

[build]
  entrypoint = "./tmp/main"
  cmd = "go build -o ./tmp/main ./cmd/api"
  delay = 1000
  exclude_dir = ["tmp", "docs", "node_modules"]
  exclude_regex = ["_test\\.go$"]
  include_ext = ["go", "yaml"]
  kill_delay = "0s"
  send_interrupt = false
  stop_on_error = true

[log]
  time = false

[misc]
  clean_on_exit = true
